version: '3.8'

services:

  # Telemetry configuration
  jaeger:
    image: diva/jaeger:${JAEGER_VERSION:-v23.8.0}
    platform: linux/amd64
    container_name: jaeger
    restart: unless-stopped
    profiles:
      - telemetry

  vector:
    image: diva/vector:${VECTOR_VERSION:-v23.8.0}
    platform: linux/amd64
    container_name: vector
    restart: unless-stopped
    profiles:
      - telemetry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - USERNAME=${TESTNET_USERNAME}
